import type { Metadata } from "next";
import "./globals.css";
import Providers from "./app";

import NavBar from "./parts/navbar";

export const metadata: Metadata = {
  title: "Food-shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
